services:

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  api:
    image: ghcr.io/edrian-a-marinas/sitesync-api:latest
    restart: always
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_CACHE_URL: ${REDIS_CACHE_URL}
      MONGO_URL: ${MONGO_URL}
    volumes:
      - ml_models:/app/app/ml/models
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy

  celery_worker:
    image: ghcr.io/edrian-a-marinas/sitesync-api:latest
    restart: always
    command: celery -A app.core.celery:celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_CACHE_URL: ${REDIS_CACHE_URL}
    volumes:
      - ml_models:/app/app/ml/models
    depends_on:
      redis:
        condition: service_healthy
        
  celery_beat:
    image: ghcr.io/edrian-a-marinas/sitesync-api:latest
    restart: always
    command: celery -A app.core.celery:celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_CACHE_URL: ${REDIS_CACHE_URL}
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mongo_data:
  ml_models: