"""add created_by to users

Revision ID: 0d199ef29d0c
Revises: df1a4e1b0d83
Create Date: 2026-06-07 09:33:31.467173

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d199ef29d0c'
down_revision: Union[str, Sequence[str], None] = 'df1a4e1b0d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
