"""remove_unique_constraint_import_cleanup

Revision ID: 1094975a8b5d
Revises: e153bb820fa5
Create Date: 2026-06-29 17:13:36.210030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1094975a8b5d'
down_revision: Union[str, Sequence[str], None] = 'e153bb820fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
