"""add_summary_columns_to_reports

Revision ID: 4c2e4cdbd1a8
Revises: b23ab7faa715
Create Date: 2026-06-25 20:35:27.670350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2e4cdbd1a8'
down_revision: Union[str, Sequence[str], None] = 'b23ab7faa715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('total_hours', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('total_material_cost', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('log_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('incident_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('open_incident_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'open_incident_count')
    op.drop_column('reports', 'incident_count')
    op.drop_column('reports', 'log_count')
    op.drop_column('reports', 'total_material_cost')
    op.drop_column('reports', 'total_hours')
    # ### end Alembic commands ###
