"""remove total_cost from materials

Revision ID: 58020a6bf968
Revises: f7e491fab587
Create Date: 2026-06-07 14:30:10.796539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58020a6bf968'
down_revision: Union[str, Sequence[str], None] = 'f7e491fab587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'total_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('total_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
