"""add missing foreign key indexes

Revision ID: 755c774f4332
Revises: 64c19084abf9
Create Date: 2026-06-18 22:37:32.423163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755c774f4332'
down_revision: Union[str, Sequence[str], None] = '64c19084abf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_queries_project_id'), 'ai_queries', ['project_id'], unique=False)
    op.create_index(op.f('ix_daily_logs_submitted_by'), 'daily_logs', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_site_photos_daily_log_id'), 'site_photos', ['daily_log_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_site_photos_daily_log_id'), table_name='site_photos')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_daily_logs_submitted_by'), table_name='daily_logs')
    op.drop_index(op.f('ix_ai_queries_project_id'), table_name='ai_queries')
    # ### end Alembic commands ###
