"""add source to reports

Revision ID: a7ffc34146a0
Revises: 4c2e4cdbd1a8
Create Date: 2026-06-27 19:21:23.650148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ffc34146a0'
down_revision: Union[str, Sequence[str], None] = '4c2e4cdbd1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'source')
    # ### end Alembic commands ###
