"""add computed total_cost to materials

Revision ID: eae5a78be3fc
Revises: 58020a6bf968
Create Date: 2026-06-07 14:35:05.097834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae5a78be3fc'
down_revision: Union[str, Sequence[str], None] = '58020a6bf968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('total_cost', sa.Numeric(precision=12, scale=2), sa.Computed('quantity * unit_cost', ), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'total_cost')
    # ### end Alembic commands ###
