"""make_generated_by_nullable_in_reports

Revision ID: ec07330d110f
Revises: 9e375583feef
Create Date: 2026-06-29 16:43:52.375061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec07330d110f'
down_revision: Union[str, Sequence[str], None] = '9e375583feef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'generated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'generated_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
