"""add ai_query_embeddings table

Revision ID: ee24bc019a40
Revises: d563f266a4e4
Create Date: 2026-07-19 15:50:19.615586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ee24bc019a40'
down_revision: Union[str, Sequence[str], None] = 'd563f266a4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_query_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_query_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_query_id'], ['ai_queries.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_query_id')
    )
    op.create_index('ix_ai_query_embeddings_embedding_hnsw', 'ai_query_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_ai_query_embeddings_project_id'), 'ai_query_embeddings', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_query_embeddings_project_id'), table_name='ai_query_embeddings')
    op.drop_index('ix_ai_query_embeddings_embedding_hnsw', table_name='ai_query_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('ai_query_embeddings')
    # ### end Alembic commands ###
